### ISSUE TITLE
Add an input parameter for role

### ISSUE THREAD

**Issue by AlisdairO** [digital-sailors/standard-redirects-for-cloudfront#3]
Hey, thanks for this work! One thing that would be useful is to make the role assigned to the lambda configurable via input parameter. This would make it possible to pull the SAR in via cloudformation without any manual work.

**Comment by zxiiro** [comment]
I proposed a PR #4 which creates a default role that includes the edgelambda trusted relationship so that this could work out of the box without requiring additional manual steps. @captain-digitalsailors what are the next steps to getting this reviewed and potentially released?
