### ISSUE TITLE
Update to Node.js 12

### ISSUE THREAD

**Issue by rayzhudev** [digital-sailors/standard-redirects-for-cloudfront#5]
[Amazon is ending support for Node.js 10.x](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html) so this package needs to be updated to Node.js 12.x (the latest version supported by lambda@edge.

**Comment by digitalkapitaen** [comment]
Has been fixed in 1.4.3. (Updated not Node.js 14.)
