### ISSUE TITLE
CWE-601: URL Redirection to Untrusted Site ('Open Redirect')

### ISSUE THREAD

**Issue by jianliao** [digital-sailors/standard-redirects-for-cloudfront#6]
Hi @digitalkapitaen,
I am from Adobe. I use this function on one of the static websites. I got a ticket from the Adobe security team about [CWE-601](https://cwe.mitre.org/data/definitions/601.html). I checked some of the forked REPOs, and the issue could be reproduced easily.

Websites | Owner | Reproduced (just an example, pls ignore the content)
--------- | ------- | -------------
https://yeonghoey.com/ | @yeonghoey | https://yeonghoey.com//adobe.design/jobs/jobpost-R109983
https://marcanuy.com/ | @marcanuy | https://marcanuy.com//adobe.design/jobs/jobpost-R109983
https://matthijslangenberg.nl/ | @mlangenberg | https://matthijslangenberg.nl//adobe.design/jobs/jobpost-R109983

I located the root cause is here:
https://github.com/digital-sailors/standard-redirects-for-cloudfront/blob/558ab482d9a28d26dd43f2b421ef24c5acb41ac1/index.js#L38-L47

A possible solution could always be replacing the first double slash with a single slash?

I noticed that there are more than 2.2k deployments for this function on AWS Serverless Application Repository. Not sure if you can let those users know about it.

**Comment by jianliao** [comment]
Original source: https://hackerone.com/reports/1189909

**Comment by digitalkapitaen** [comment]
Has been fixed in 1.4.2.
